# Generated by Django 5.0.3 on 2024-03-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('status', models.CharField(choices=[('S', 'SINGLE'), ('M', 'MARRIED'), ('SXC', 'MARRIED-EXCONVICT'), ('MXC', 'MARRIED-EXCONVICT')], max_length=6)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=20)),
                ('hair_color', models.CharField(max_length=20)),
                ('health_concerns', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='prisoners/')),
                ('date_arrested', models.DateField()),
                ('magistrate_first_name', models.CharField(max_length=50)),
                ('magistrate_last_name', models.CharField(max_length=50)),
                ('court', models.CharField(max_length=50)),
                ('crime_committed', models.CharField(max_length=50)),
                ('category_of_offense', models.CharField(choices=[('SE', 'SEVERE'), ('FE', 'FELONY')], max_length=6)),
                ('case_start_date', models.DateField()),
                ('case_end_date', models.DateField()),
                ('sentence', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.Cell')),
            ],
        ),
    ]
