# Generated by Django 5.0.3 on 2024-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_alter_cell_name_prisoner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='sentence',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], max_length=8),
        ),
    ]
