# Generated by Django 5.0.3 on 2024-03-30 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0003_alter_prisoner_sentence_alter_prisoner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='category_of_offense',
            field=models.CharField(choices=[('SEVERE', 'SEVERE'), ('FELONY', 'FELONY')], max_length=6),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8),
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('photo', models.ImageField(upload_to='guards/')),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], max_length=20)),
                ('shift_start_time', models.DateTimeField()),
                ('shift_end_time', models.DateTimeField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('phone_number', models.CharField(max_length=25)),
                ('date_visited', models.DateField()),
                ('time_of_arrival', models.DateTimeField()),
                ('time_of_departure', models.DateTimeField()),
                ('cell_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell')),
                ('prisoner_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.prisoner')),
            ],
        ),
    ]
