# Generated by Django 5.0.3 on 2024-04-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0005_alter_guard_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cell_visited',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='prisoner_visited',
            field=models.CharField(max_length=100),
        ),
    ]
