# Generated by Django 5.0.3 on 2024-04-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0006_alter_visitor_cell_visited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='guard',
            name='marital_status',
        ),
        migrations.AlterField(
            model_name='guard',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='category_of_offense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.offense'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.status'),
        ),
    ]
