# Generated by Django 5.0.3 on 2024-04-20 07:17

import prison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0007_gender_offense_status_remove_guard_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='gender',
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=prison.models.filepath),
        ),
    ]
