# Generated by Django 5.0.3 on 2024-04-20 07:50

import django.db.models.deletion
import prison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0008_remove_visitor_gender_alter_prisoner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='guard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=prison.models.filepath),
        ),
    ]
