# Generated by Django 5.0.3 on 2024-04-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0009_visitor_gender_alter_gender_name_alter_guard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cell_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='prisoner_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.prisoner'),
        ),
    ]
