# Generated by Django 5.0.3 on 2024-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0010_alter_visitor_cell_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
