# Generated by Django 5.0.3 on 2024-04-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0011_alter_visitor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
