# Generated by Django 5.0.3 on 2024-05-08 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0016_alter_cell_name_alter_prisoner_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='guard',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell', to_field='name'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender', to_field='name'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='category_of_offense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.offense', to_field='name'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender', to_field='name'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.status', to_field='name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cell_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell', to_field='name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender', to_field='name'),
        ),
    ]
