# Generated by Django 5.0.3 on 2024-05-08 01:24

import django.db.models.deletion
import prison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0017_alter_gender_name_alter_guard_cell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='case_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='case_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='category_of_offense',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prison.offense', to_field='name'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='court',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='magistrate_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='magistrate_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='photo',
            field=models.ImageField(null=True, upload_to=prison.models.filepath),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='sentence',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
