# Generated by Django 5.0.3 on 2024-05-08 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0019_alter_prisoner_category_of_offense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell', to_field='name'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender', to_field='name'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.status', to_field='name'),
        ),
    ]
