# Generated by Django 5.0.3 on 2024-05-23 04:33

import prison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0021_alter_prisoner_cell_alter_prisoner_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='photo',
            field=models.ImageField(null=True, upload_to=prison.models.filepath),
        ),
    ]
