# Generated by Django 5.0.3 on 2024-05-23 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0022_alter_guard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
    ]
