# Generated by Django 5.0.3 on 2024-05-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0023_alter_guard_cell_alter_guard_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cell_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.cell'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.gender'),
        ),
    ]
